// Generated by gencpp from file uav_control/DeadlockInfo.msg
// DO NOT EDIT!


#ifndef UAV_CONTROL_MESSAGE_DEADLOCKINFO_H
#define UAV_CONTROL_MESSAGE_DEADLOCKINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_control
{
template <class ContainerAllocator>
struct DeadlockInfo_
{
  typedef DeadlockInfo_<ContainerAllocator> Type;

  DeadlockInfo_()
    : blocker_id()
    , blocked_id()
    , is_bilateral(false)  {
    }
  DeadlockInfo_(const ContainerAllocator& _alloc)
    : blocker_id(_alloc)
    , blocked_id(_alloc)
    , is_bilateral(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _blocker_id_type;
  _blocker_id_type blocker_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _blocked_id_type;
  _blocked_id_type blocked_id;

   typedef uint8_t _is_bilateral_type;
  _is_bilateral_type is_bilateral;





  typedef boost::shared_ptr< ::uav_control::DeadlockInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_control::DeadlockInfo_<ContainerAllocator> const> ConstPtr;

}; // struct DeadlockInfo_

typedef ::uav_control::DeadlockInfo_<std::allocator<void> > DeadlockInfo;

typedef boost::shared_ptr< ::uav_control::DeadlockInfo > DeadlockInfoPtr;
typedef boost::shared_ptr< ::uav_control::DeadlockInfo const> DeadlockInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_control::DeadlockInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_control::DeadlockInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_control::DeadlockInfo_<ContainerAllocator1> & lhs, const ::uav_control::DeadlockInfo_<ContainerAllocator2> & rhs)
{
  return lhs.blocker_id == rhs.blocker_id &&
    lhs.blocked_id == rhs.blocked_id &&
    lhs.is_bilateral == rhs.is_bilateral;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_control::DeadlockInfo_<ContainerAllocator1> & lhs, const ::uav_control::DeadlockInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_control::DeadlockInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_control::DeadlockInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_control::DeadlockInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_control::DeadlockInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_control::DeadlockInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_control::DeadlockInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_control::DeadlockInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "38f3084008c30c3c1c815f245eba16b8";
  }

  static const char* value(const ::uav_control::DeadlockInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x38f3084008c30c3cULL;
  static const uint64_t static_value2 = 0x1c815f245eba16b8ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_control::DeadlockInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_control/DeadlockInfo";
  }

  static const char* value(const ::uav_control::DeadlockInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_control::DeadlockInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string blocker_id    # 造成阻塞的无人机ID\n"
"string blocked_id   # 被阻塞的无人机ID\n"
"bool is_bilateral   # true表示双向死锁，false表示单向阻塞\n"
;
  }

  static const char* value(const ::uav_control::DeadlockInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_control::DeadlockInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.blocker_id);
      stream.next(m.blocked_id);
      stream.next(m.is_bilateral);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeadlockInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_control::DeadlockInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_control::DeadlockInfo_<ContainerAllocator>& v)
  {
    s << indent << "blocker_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.blocker_id);
    s << indent << "blocked_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.blocked_id);
    s << indent << "is_bilateral: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_bilateral);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_CONTROL_MESSAGE_DEADLOCKINFO_H
