// Generated by gencpp from file uav_control/LDRCompletion.msg
// DO NOT EDIT!


#ifndef UAV_CONTROL_MESSAGE_LDRCOMPLETION_H
#define UAV_CONTROL_MESSAGE_LDRCOMPLETION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace uav_control
{
template <class ContainerAllocator>
struct LDRCompletion_
{
  typedef LDRCompletion_<ContainerAllocator> Type;

  LDRCompletion_()
    : header()
    , ldr_id(0)
    , uav_ids()
    , message()  {
    }
  LDRCompletion_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ldr_id(0)
    , uav_ids(_alloc)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _ldr_id_type;
  _ldr_id_type ldr_id;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _uav_ids_type;
  _uav_ids_type uav_ids;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::uav_control::LDRCompletion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_control::LDRCompletion_<ContainerAllocator> const> ConstPtr;

}; // struct LDRCompletion_

typedef ::uav_control::LDRCompletion_<std::allocator<void> > LDRCompletion;

typedef boost::shared_ptr< ::uav_control::LDRCompletion > LDRCompletionPtr;
typedef boost::shared_ptr< ::uav_control::LDRCompletion const> LDRCompletionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_control::LDRCompletion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_control::LDRCompletion_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_control::LDRCompletion_<ContainerAllocator1> & lhs, const ::uav_control::LDRCompletion_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ldr_id == rhs.ldr_id &&
    lhs.uav_ids == rhs.uav_ids &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_control::LDRCompletion_<ContainerAllocator1> & lhs, const ::uav_control::LDRCompletion_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_control::LDRCompletion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_control::LDRCompletion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_control::LDRCompletion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_control::LDRCompletion_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_control::LDRCompletion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_control::LDRCompletion_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_control::LDRCompletion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6ac87e9767065ecacf77bb14cf02fd4";
  }

  static const char* value(const ::uav_control::LDRCompletion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6ac87e9767065ecULL;
  static const uint64_t static_value2 = 0xacf77bb14cf02fd4ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_control::LDRCompletion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_control/LDRCompletion";
  }

  static const char* value(const ::uav_control::LDRCompletion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_control::LDRCompletion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# LDR完成广播消息\n"
"Header header\n"
"int32 ldr_id\n"
"string[] uav_ids\n"
"string message\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::uav_control::LDRCompletion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_control::LDRCompletion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ldr_id);
      stream.next(m.uav_ids);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LDRCompletion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_control::LDRCompletion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_control::LDRCompletion_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ldr_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ldr_id);
    s << indent << "uav_ids[]" << std::endl;
    for (size_t i = 0; i < v.uav_ids.size(); ++i)
    {
      s << indent << "  uav_ids[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.uav_ids[i]);
    }
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_CONTROL_MESSAGE_LDRCOMPLETION_H
