// Generated by gencpp from file uav_control/PathPlan.msg
// DO NOT EDIT!


#ifndef UAV_CONTROL_MESSAGE_PATHPLAN_H
#define UAV_CONTROL_MESSAGE_PATHPLAN_H

#include <ros/service_traits.h>


#include <uav_control/PathPlanRequest.h>
#include <uav_control/PathPlanResponse.h>


namespace uav_control
{

struct PathPlan
{

typedef PathPlanRequest Request;
typedef PathPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathPlan
} // namespace uav_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_control::PathPlan > {
  static const char* value()
  {
    return "c9c9ee362512ec5be6042c67e74ac40f";
  }

  static const char* value(const ::uav_control::PathPlan&) { return value(); }
};

template<>
struct DataType< ::uav_control::PathPlan > {
  static const char* value()
  {
    return "uav_control/PathPlan";
  }

  static const char* value(const ::uav_control::PathPlan&) { return value(); }
};


// service_traits::MD5Sum< ::uav_control::PathPlanRequest> should match
// service_traits::MD5Sum< ::uav_control::PathPlan >
template<>
struct MD5Sum< ::uav_control::PathPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_control::PathPlan >::value();
  }
  static const char* value(const ::uav_control::PathPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_control::PathPlanRequest> should match
// service_traits::DataType< ::uav_control::PathPlan >
template<>
struct DataType< ::uav_control::PathPlanRequest>
{
  static const char* value()
  {
    return DataType< ::uav_control::PathPlan >::value();
  }
  static const char* value(const ::uav_control::PathPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_control::PathPlanResponse> should match
// service_traits::MD5Sum< ::uav_control::PathPlan >
template<>
struct MD5Sum< ::uav_control::PathPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_control::PathPlan >::value();
  }
  static const char* value(const ::uav_control::PathPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_control::PathPlanResponse> should match
// service_traits::DataType< ::uav_control::PathPlan >
template<>
struct DataType< ::uav_control::PathPlanResponse>
{
  static const char* value()
  {
    return DataType< ::uav_control::PathPlan >::value();
  }
  static const char* value(const ::uav_control::PathPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_CONTROL_MESSAGE_PATHPLAN_H
