// Generated by gencpp from file uav_control/PathTrackingRequest.msg
// DO NOT EDIT!


#ifndef UAV_CONTROL_MESSAGE_PATHTRACKINGREQUEST_H
#define UAV_CONTROL_MESSAGE_PATHTRACKINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <uav_control/UAVPath.h>

namespace uav_control
{
template <class ContainerAllocator>
struct PathTrackingRequest_
{
  typedef PathTrackingRequest_<ContainerAllocator> Type;

  PathTrackingRequest_()
    : header()
    , ldr_id(0)
    , uav_ids()
    , uav_paths()  {
    }
  PathTrackingRequest_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ldr_id(0)
    , uav_ids(_alloc)
    , uav_paths(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _ldr_id_type;
  _ldr_id_type ldr_id;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _uav_ids_type;
  _uav_ids_type uav_ids;

   typedef std::vector< ::uav_control::UAVPath_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::uav_control::UAVPath_<ContainerAllocator> >> _uav_paths_type;
  _uav_paths_type uav_paths;





  typedef boost::shared_ptr< ::uav_control::PathTrackingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_control::PathTrackingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PathTrackingRequest_

typedef ::uav_control::PathTrackingRequest_<std::allocator<void> > PathTrackingRequest;

typedef boost::shared_ptr< ::uav_control::PathTrackingRequest > PathTrackingRequestPtr;
typedef boost::shared_ptr< ::uav_control::PathTrackingRequest const> PathTrackingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_control::PathTrackingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_control::PathTrackingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_control::PathTrackingRequest_<ContainerAllocator1> & lhs, const ::uav_control::PathTrackingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ldr_id == rhs.ldr_id &&
    lhs.uav_ids == rhs.uav_ids &&
    lhs.uav_paths == rhs.uav_paths;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_control::PathTrackingRequest_<ContainerAllocator1> & lhs, const ::uav_control::PathTrackingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_control::PathTrackingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_control::PathTrackingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_control::PathTrackingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_control::PathTrackingRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_control::PathTrackingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_control::PathTrackingRequest_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_control::PathTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66074861de72e89556e85750791c9c7b";
  }

  static const char* value(const ::uav_control::PathTrackingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66074861de72e895ULL;
  static const uint64_t static_value2 = 0x56e85750791c9c7bULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_control::PathTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_control/PathTrackingRequest";
  }

  static const char* value(const ::uav_control::PathTrackingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_control::PathTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# PathTracking.srv\n"
"# 路径跟踪服务定义\n"
"\n"
"# Request - 发送路径信息\n"
"std_msgs/Header header\n"
"int32 ldr_id\n"
"string[] uav_ids\n"
"uav_control/UAVPath[] uav_paths\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: uav_control/UAVPath\n"
"# 单个无人机的路径信息\n"
"# 文件路径: uav_control/msg/UAVPath.msg\n"
"\n"
"string uav_id\n"
"geometry_msgs/Point[] path_points\n"
"int32[] time_indices\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::uav_control::PathTrackingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_control::PathTrackingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ldr_id);
      stream.next(m.uav_ids);
      stream.next(m.uav_paths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathTrackingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_control::PathTrackingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_control::PathTrackingRequest_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ldr_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ldr_id);
    s << indent << "uav_ids[]" << std::endl;
    for (size_t i = 0; i < v.uav_ids.size(); ++i)
    {
      s << indent << "  uav_ids[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.uav_ids[i]);
    }
    s << indent << "uav_paths[]" << std::endl;
    for (size_t i = 0; i < v.uav_paths.size(); ++i)
    {
      s << indent << "  uav_paths[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::uav_control::UAVPath_<ContainerAllocator> >::stream(s, indent + "    ", v.uav_paths[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_CONTROL_MESSAGE_PATHTRACKINGREQUEST_H
