// Generated by gencpp from file uav_control/PathTracking.msg
// DO NOT EDIT!


#ifndef UAV_CONTROL_MESSAGE_PATHTRACKING_H
#define UAV_CONTROL_MESSAGE_PATHTRACKING_H

#include <ros/service_traits.h>


#include <uav_control/PathTrackingRequest.h>
#include <uav_control/PathTrackingResponse.h>


namespace uav_control
{

struct PathTracking
{

typedef PathTrackingRequest Request;
typedef PathTrackingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathTracking
} // namespace uav_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uav_control::PathTracking > {
  static const char* value()
  {
    return "0ff8a4c9efe935b06b349c3681633f16";
  }

  static const char* value(const ::uav_control::PathTracking&) { return value(); }
};

template<>
struct DataType< ::uav_control::PathTracking > {
  static const char* value()
  {
    return "uav_control/PathTracking";
  }

  static const char* value(const ::uav_control::PathTracking&) { return value(); }
};


// service_traits::MD5Sum< ::uav_control::PathTrackingRequest> should match
// service_traits::MD5Sum< ::uav_control::PathTracking >
template<>
struct MD5Sum< ::uav_control::PathTrackingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uav_control::PathTracking >::value();
  }
  static const char* value(const ::uav_control::PathTrackingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_control::PathTrackingRequest> should match
// service_traits::DataType< ::uav_control::PathTracking >
template<>
struct DataType< ::uav_control::PathTrackingRequest>
{
  static const char* value()
  {
    return DataType< ::uav_control::PathTracking >::value();
  }
  static const char* value(const ::uav_control::PathTrackingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uav_control::PathTrackingResponse> should match
// service_traits::MD5Sum< ::uav_control::PathTracking >
template<>
struct MD5Sum< ::uav_control::PathTrackingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uav_control::PathTracking >::value();
  }
  static const char* value(const ::uav_control::PathTrackingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uav_control::PathTrackingResponse> should match
// service_traits::DataType< ::uav_control::PathTracking >
template<>
struct DataType< ::uav_control::PathTrackingResponse>
{
  static const char* value()
  {
    return DataType< ::uav_control::PathTracking >::value();
  }
  static const char* value(const ::uav_control::PathTrackingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UAV_CONTROL_MESSAGE_PATHTRACKING_H
