// Generated by gencpp from file uav_control/PathPlanResponse.msg
// DO NOT EDIT!


#ifndef UAV_CONTROL_MESSAGE_PATHPLANRESPONSE_H
#define UAV_CONTROL_MESSAGE_PATHPLANRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace uav_control
{
template <class ContainerAllocator>
struct PathPlanResponse_
{
  typedef PathPlanResponse_<ContainerAllocator> Type;

  PathPlanResponse_()
    : success(false)
    , message()
    , path()  {
    }
  PathPlanResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::uav_control::PathPlanResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_control::PathPlanResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PathPlanResponse_

typedef ::uav_control::PathPlanResponse_<std::allocator<void> > PathPlanResponse;

typedef boost::shared_ptr< ::uav_control::PathPlanResponse > PathPlanResponsePtr;
typedef boost::shared_ptr< ::uav_control::PathPlanResponse const> PathPlanResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_control::PathPlanResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_control::PathPlanResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_control::PathPlanResponse_<ContainerAllocator1> & lhs, const ::uav_control::PathPlanResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_control::PathPlanResponse_<ContainerAllocator1> & lhs, const ::uav_control::PathPlanResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_control::PathPlanResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_control::PathPlanResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_control::PathPlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_control::PathPlanResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_control::PathPlanResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_control::PathPlanResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_control::PathPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7dcb9d698f920b09092283d36a2c9f3";
  }

  static const char* value(const ::uav_control::PathPlanResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7dcb9d698f920b0ULL;
  static const uint64_t static_value2 = 0x9092283d36a2c9f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_control::PathPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_control/PathPlanResponse";
  }

  static const char* value(const ::uav_control::PathPlanResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_control::PathPlanResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"string message\n"
"geometry_msgs/Point[] path\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::uav_control::PathPlanResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_control::PathPlanResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathPlanResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_control::PathPlanResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_control::PathPlanResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_CONTROL_MESSAGE_PATHPLANRESPONSE_H
