// Generated by gencpp from file uav_control/PathTrackingResponse.msg
// DO NOT EDIT!


#ifndef UAV_CONTROL_MESSAGE_PATHTRACKINGRESPONSE_H
#define UAV_CONTROL_MESSAGE_PATHTRACKINGRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_control
{
template <class ContainerAllocator>
struct PathTrackingResponse_
{
  typedef PathTrackingResponse_<ContainerAllocator> Type;

  PathTrackingResponse_()
    : success(false)
    , message()
    , execution_time(0.0)  {
    }
  PathTrackingResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , execution_time(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef double _execution_time_type;
  _execution_time_type execution_time;





  typedef boost::shared_ptr< ::uav_control::PathTrackingResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_control::PathTrackingResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PathTrackingResponse_

typedef ::uav_control::PathTrackingResponse_<std::allocator<void> > PathTrackingResponse;

typedef boost::shared_ptr< ::uav_control::PathTrackingResponse > PathTrackingResponsePtr;
typedef boost::shared_ptr< ::uav_control::PathTrackingResponse const> PathTrackingResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_control::PathTrackingResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_control::PathTrackingResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_control::PathTrackingResponse_<ContainerAllocator1> & lhs, const ::uav_control::PathTrackingResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.execution_time == rhs.execution_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_control::PathTrackingResponse_<ContainerAllocator1> & lhs, const ::uav_control::PathTrackingResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_control::PathTrackingResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_control::PathTrackingResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_control::PathTrackingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_control::PathTrackingResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_control::PathTrackingResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_control::PathTrackingResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_control::PathTrackingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8dc547cb16b95701f3b64b7c9a288908";
  }

  static const char* value(const ::uav_control::PathTrackingResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8dc547cb16b95701ULL;
  static const uint64_t static_value2 = 0xf3b64b7c9a288908ULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_control::PathTrackingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_control/PathTrackingResponse";
  }

  static const char* value(const ::uav_control::PathTrackingResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_control::PathTrackingResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"# Response - 返回执行结果\n"
"bool success\n"
"string message\n"
"float64 execution_time\n"
;
  }

  static const char* value(const ::uav_control::PathTrackingResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_control::PathTrackingResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.execution_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathTrackingResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_control::PathTrackingResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_control::PathTrackingResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "execution_time: ";
    Printer<double>::stream(s, indent + "  ", v.execution_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_CONTROL_MESSAGE_PATHTRACKINGRESPONSE_H
