// Generated by gencpp from file uav_control/StopCommand.msg
// DO NOT EDIT!


#ifndef UAV_CONTROL_MESSAGE_STOPCOMMAND_H
#define UAV_CONTROL_MESSAGE_STOPCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uav_control
{
template <class ContainerAllocator>
struct StopCommand_
{
  typedef StopCommand_<ContainerAllocator> Type;

  StopCommand_()
    : stop(false)
    , blocker_id()  {
    }
  StopCommand_(const ContainerAllocator& _alloc)
    : stop(false)
    , blocker_id(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _stop_type;
  _stop_type stop;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _blocker_id_type;
  _blocker_id_type blocker_id;





  typedef boost::shared_ptr< ::uav_control::StopCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uav_control::StopCommand_<ContainerAllocator> const> ConstPtr;

}; // struct StopCommand_

typedef ::uav_control::StopCommand_<std::allocator<void> > StopCommand;

typedef boost::shared_ptr< ::uav_control::StopCommand > StopCommandPtr;
typedef boost::shared_ptr< ::uav_control::StopCommand const> StopCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uav_control::StopCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uav_control::StopCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::uav_control::StopCommand_<ContainerAllocator1> & lhs, const ::uav_control::StopCommand_<ContainerAllocator2> & rhs)
{
  return lhs.stop == rhs.stop &&
    lhs.blocker_id == rhs.blocker_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::uav_control::StopCommand_<ContainerAllocator1> & lhs, const ::uav_control::StopCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace uav_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::uav_control::StopCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uav_control::StopCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_control::StopCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uav_control::StopCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_control::StopCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uav_control::StopCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uav_control::StopCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ee931530b17c39eb5a3b97eb6933cbd";
  }

  static const char* value(const ::uav_control::StopCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ee931530b17c39eULL;
  static const uint64_t static_value2 = 0xb5a3b97eb6933cbdULL;
};

template<class ContainerAllocator>
struct DataType< ::uav_control::StopCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uav_control/StopCommand";
  }

  static const char* value(const ::uav_control::StopCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uav_control::StopCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool stop\n"
"string blocker_id  # 导致死锁的无人机ID\n"
;
  }

  static const char* value(const ::uav_control::StopCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uav_control::StopCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stop);
      stream.next(m.blocker_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StopCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uav_control::StopCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uav_control::StopCommand_<ContainerAllocator>& v)
  {
    s << indent << "stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop);
    s << indent << "blocker_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.blocker_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UAV_CONTROL_MESSAGE_STOPCOMMAND_H
