// Generated by gencpp from file quad_star/PathPlan.msg
// DO NOT EDIT!


#ifndef QUAD_STAR_MESSAGE_PATHPLAN_H
#define QUAD_STAR_MESSAGE_PATHPLAN_H

#include <ros/service_traits.h>


#include <quad_star/PathPlanRequest.h>
#include <quad_star/PathPlanResponse.h>


namespace quad_star
{

struct PathPlan
{

typedef PathPlanRequest Request;
typedef PathPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathPlan
} // namespace quad_star


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::quad_star::PathPlan > {
  static const char* value()
  {
    return "c9c9ee362512ec5be6042c67e74ac40f";
  }

  static const char* value(const ::quad_star::PathPlan&) { return value(); }
};

template<>
struct DataType< ::quad_star::PathPlan > {
  static const char* value()
  {
    return "quad_star/PathPlan";
  }

  static const char* value(const ::quad_star::PathPlan&) { return value(); }
};


// service_traits::MD5Sum< ::quad_star::PathPlanRequest> should match
// service_traits::MD5Sum< ::quad_star::PathPlan >
template<>
struct MD5Sum< ::quad_star::PathPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::quad_star::PathPlan >::value();
  }
  static const char* value(const ::quad_star::PathPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::quad_star::PathPlanRequest> should match
// service_traits::DataType< ::quad_star::PathPlan >
template<>
struct DataType< ::quad_star::PathPlanRequest>
{
  static const char* value()
  {
    return DataType< ::quad_star::PathPlan >::value();
  }
  static const char* value(const ::quad_star::PathPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::quad_star::PathPlanResponse> should match
// service_traits::MD5Sum< ::quad_star::PathPlan >
template<>
struct MD5Sum< ::quad_star::PathPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::quad_star::PathPlan >::value();
  }
  static const char* value(const ::quad_star::PathPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::quad_star::PathPlanResponse> should match
// service_traits::DataType< ::quad_star::PathPlan >
template<>
struct DataType< ::quad_star::PathPlanResponse>
{
  static const char* value()
  {
    return DataType< ::quad_star::PathPlan >::value();
  }
  static const char* value(const ::quad_star::PathPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QUAD_STAR_MESSAGE_PATHPLAN_H
