// Generated by gencpp from file quad_star/SimplePathPlan.msg
// DO NOT EDIT!


#ifndef QUAD_STAR_MESSAGE_SIMPLEPATHPLAN_H
#define QUAD_STAR_MESSAGE_SIMPLEPATHPLAN_H

#include <ros/service_traits.h>


#include <quad_star/SimplePathPlanRequest.h>
#include <quad_star/SimplePathPlanResponse.h>


namespace quad_star
{

struct SimplePathPlan
{

typedef SimplePathPlanRequest Request;
typedef SimplePathPlanResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SimplePathPlan
} // namespace quad_star


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::quad_star::SimplePathPlan > {
  static const char* value()
  {
    return "cc0fa8f370b2645f29bc836e78ed2538";
  }

  static const char* value(const ::quad_star::SimplePathPlan&) { return value(); }
};

template<>
struct DataType< ::quad_star::SimplePathPlan > {
  static const char* value()
  {
    return "quad_star/SimplePathPlan";
  }

  static const char* value(const ::quad_star::SimplePathPlan&) { return value(); }
};


// service_traits::MD5Sum< ::quad_star::SimplePathPlanRequest> should match
// service_traits::MD5Sum< ::quad_star::SimplePathPlan >
template<>
struct MD5Sum< ::quad_star::SimplePathPlanRequest>
{
  static const char* value()
  {
    return MD5Sum< ::quad_star::SimplePathPlan >::value();
  }
  static const char* value(const ::quad_star::SimplePathPlanRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::quad_star::SimplePathPlanRequest> should match
// service_traits::DataType< ::quad_star::SimplePathPlan >
template<>
struct DataType< ::quad_star::SimplePathPlanRequest>
{
  static const char* value()
  {
    return DataType< ::quad_star::SimplePathPlan >::value();
  }
  static const char* value(const ::quad_star::SimplePathPlanRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::quad_star::SimplePathPlanResponse> should match
// service_traits::MD5Sum< ::quad_star::SimplePathPlan >
template<>
struct MD5Sum< ::quad_star::SimplePathPlanResponse>
{
  static const char* value()
  {
    return MD5Sum< ::quad_star::SimplePathPlan >::value();
  }
  static const char* value(const ::quad_star::SimplePathPlanResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::quad_star::SimplePathPlanResponse> should match
// service_traits::DataType< ::quad_star::SimplePathPlan >
template<>
struct DataType< ::quad_star::SimplePathPlanResponse>
{
  static const char* value()
  {
    return DataType< ::quad_star::SimplePathPlan >::value();
  }
  static const char* value(const ::quad_star::SimplePathPlanResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QUAD_STAR_MESSAGE_SIMPLEPATHPLAN_H
