# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uav_control/DeadlockInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DeadlockInfo(genpy.Message):
  _md5sum = "38f3084008c30c3c1c815f245eba16b8"
  _type = "uav_control/DeadlockInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string blocker_id    # 造成阻塞的无人机ID
string blocked_id   # 被阻塞的无人机ID
bool is_bilateral   # true表示双向死锁，false表示单向阻塞"""
  __slots__ = ['blocker_id','blocked_id','is_bilateral']
  _slot_types = ['string','string','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       blocker_id,blocked_id,is_bilateral

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DeadlockInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.blocker_id is None:
        self.blocker_id = ''
      if self.blocked_id is None:
        self.blocked_id = ''
      if self.is_bilateral is None:
        self.is_bilateral = False
    else:
      self.blocker_id = ''
      self.blocked_id = ''
      self.is_bilateral = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.blocker_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.blocked_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.is_bilateral
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.blocker_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.blocker_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.blocked_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.blocked_id = str[start:end]
      start = end
      end += 1
      (self.is_bilateral,) = _get_struct_B().unpack(str[start:end])
      self.is_bilateral = bool(self.is_bilateral)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.blocker_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.blocked_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.is_bilateral
      buff.write(_get_struct_B().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.blocker_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.blocker_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.blocked_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.blocked_id = str[start:end]
      start = end
      end += 1
      (self.is_bilateral,) = _get_struct_B().unpack(str[start:end])
      self.is_bilateral = bool(self.is_bilateral)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
