# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uav_control/LDRInfoArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import uav_control.msg

class LDRInfoArray(genpy.Message):
  _md5sum = "9e49ba5991a82a17025c4ca6b278a4e1"
  _type = "uav_control/LDRInfoArray"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uav_control/LDRInfo[] ldr_infos
================================================================================
MSG: uav_control/LDRInfo
string[] uav_ids
geometry_msgs/Point[] positions
float64 min_x
float64 max_x
float64 min_y
float64 max_y
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['ldr_infos']
  _slot_types = ['uav_control/LDRInfo[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ldr_infos

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(LDRInfoArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ldr_infos is None:
        self.ldr_infos = []
    else:
      self.ldr_infos = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.ldr_infos)
      buff.write(_struct_I.pack(length))
      for val1 in self.ldr_infos:
        length = len(val1.uav_ids)
        buff.write(_struct_I.pack(length))
        for val2 in val1.uav_ids:
          length = len(val2)
          if python3 or type(val2) == unicode:
            val2 = val2.encode('utf-8')
            length = len(val2)
          buff.write(struct.Struct('<I%ss'%length).pack(length, val2))
        length = len(val1.positions)
        buff.write(_struct_I.pack(length))
        for val2 in val1.positions:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_4d().pack(_x.min_x, _x.max_x, _x.min_y, _x.max_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ldr_infos is None:
        self.ldr_infos = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ldr_infos = []
      for i in range(0, length):
        val1 = uav_control.msg.LDRInfo()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.uav_ids = []
        for i in range(0, length):
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2 = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2 = str[start:end]
          val1.uav_ids.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.positions = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.positions.append(val2)
        _x = val1
        start = end
        end += 32
        (_x.min_x, _x.max_x, _x.min_y, _x.max_y,) = _get_struct_4d().unpack(str[start:end])
        self.ldr_infos.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.ldr_infos)
      buff.write(_struct_I.pack(length))
      for val1 in self.ldr_infos:
        length = len(val1.uav_ids)
        buff.write(_struct_I.pack(length))
        for val2 in val1.uav_ids:
          length = len(val2)
          if python3 or type(val2) == unicode:
            val2 = val2.encode('utf-8')
            length = len(val2)
          buff.write(struct.Struct('<I%ss'%length).pack(length, val2))
        length = len(val1.positions)
        buff.write(_struct_I.pack(length))
        for val2 in val1.positions:
          _x = val2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = val1
        buff.write(_get_struct_4d().pack(_x.min_x, _x.max_x, _x.min_y, _x.max_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.ldr_infos is None:
        self.ldr_infos = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ldr_infos = []
      for i in range(0, length):
        val1 = uav_control.msg.LDRInfo()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.uav_ids = []
        for i in range(0, length):
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2 = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2 = str[start:end]
          val1.uav_ids.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.positions = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point()
          _x = val2
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          val1.positions.append(val2)
        _x = val1
        start = end
        end += 32
        (_x.min_x, _x.max_x, _x.min_y, _x.max_y,) = _get_struct_4d().unpack(str[start:end])
        self.ldr_infos.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
